Bench imagegen (#2683)
* I hate magic numbers

* checkpoint image benchmark work-in-progress

* Dynamic formatting of benchmark results

Maybe I should use shorter model and scenario names...

* Capture output

* don't export implementation details

* correctly pass the image generation parameters into the benchmark

* Check model type against benchmark type; don't run nonsense combinations

```
./lemonade bench Z-Image-TurboQ8 SD-Turbo Flux-2-Klein-4B SD-1.5 --scenarios chat --scenario-file resources/bench_scenarios.json --runs 1

=== [Z-Image-TurboQ8] sd-cpp/rocm ===
  Scenario: chat-short (chat)
    Skipping backend - not suitable for chat scenario
  Scenario: chat-long-output (chat)
    Skipping backend - not suitable for chat scenario

=== [Z-Image-TurboQ8] sd-cpp/vulkan ===
  Scenario: chat-short (chat)
    Skipping backend - not suitable for chat scenario
  Scenario: chat-long-output (chat)
    Skipping backend - not suitable for chat scenario
Error: No benchmark results for model 'Z-Image-TurboQ8' (all backends failed to load).
```

compared to

```
./lemonade --host ryzen bench Z-Image-TurboQ SD-Turbo Flux-2-Klein-4B SD-1.5 --scenarios imagegen --scenario-file resources/bench_scenarios.json --runs 1

=== [Z-Image-TurboQ] sd-cpp/rocm ===
  Scenario: image-sd-turbo-quick (imagegen)
  Loading model with sd-cpp/rocm... done
    Run 1/1...  TTFT=7010.6ms TPS=0.0
  Scenario: image-photoreal-outdoor (imagegen)
  Loading model with sd-cpp/rocm... done
    Run 1/1...    Image generation benchmark run failed: Could not connect to Lemonade server (Failed to read connection).
Make sure the server is running and try again.
 FAILED (excluded from stats)

=== [Z-Image-TurboQ] sd-cpp/vulkan ===
  Scenario: image-sd-turbo-quick (imagegen)
  Loading model with sd-cpp/vulkan... done
    Run 1/1... TTFT=6774.8ms TPS=0.0
  Scenario: image-photoreal-outdoor (imagegen)
  Loading model with sd-cpp/vulkan... done
    Run 1/1... TTFT=22589.9ms TPS=0.0

=== [SD-Turbo] sd-cpp/rocm ===
  Scenario: image-sd-turbo-quick (imagegen)
  Loading model with sd-cpp/rocm... done
    Run 1/1... TTFT=1835.7ms TPS=0.0
  Scenario: image-photoreal-outdoor (imagegen)
  Loading model with sd-cpp/rocm... done
    Run 1/1... TTFT=5730.1ms TPS=0.0

=== [SD-Turbo] sd-cpp/vulkan ===
  Scenario: image-sd-turbo-quick (imagegen)
  Loading model with sd-cpp/vulkan... done
    Run 1/1... TTFT=1848.9ms TPS=0.0
  Scenario: image-photoreal-outdoor (imagegen)
  Loading model with sd-cpp/vulkan... done
    Run 1/1... TTFT=6242.9ms TPS=0.0
...
```

* use default steps and cfg_scale

* Fix column width autoscaling

```
Benchmark: Z-Image-TurboQ8
====================================================================================================

Backend: sd-cpp/rocm
----------------------------------------------------------------------------------------------------
Scenario            TTFT     min      max      TPS      min      max      VRAM (GB)
----------------------------------------------------------------------------------------------------
image-small         4678.6   4678.6   4678.6   0.0      0.0      0.0      10.9
image-medium        29465.8  29465.8  29465.8  0.0      0.0      0.0      10.9
image-large         126031.9 126031.9 126031.9 0.0      0.0      0.0      10.8

Backend: sd-cpp/vulkan
----------------------------------------------------------------------------------------------------
Scenario            TTFT     min      max      TPS      min      max      VRAM (GB)
----------------------------------------------------------------------------------------------------
image-small         4676.9   4676.9   4676.9   0.0      0.0      0.0      10.9
image-medium        29911.0  29911.0  29911.0  0.0      0.0      0.0      10.9
image-large         126072.2 126072.2 126072.2 0.0      0.0      0.0      10.9
```

* fix compile on windows

* wording fix

* track elapsed duration

* more image generation tests

A bunch of text drawing scenarios. Some work fairly well, some produce
comical nonsense. Some other image drawings (64kpx, 1mpx) that, in the
words of Strange Planet, "imagine pleasant nonsense".

* better parameter handling

* add a timeout argument to extend the time a request can take

Qwen-Image-2512 takes over 5 minutes to generate a 512x512 image on
my laptop, compared to 1 minute or less for Flux or Z-Image. If it's
taking that long, it better be generating winning lottery numbers.

* fix scenario name

* better filtering

running a command like
`lemonade bench nomic-embed-text-v1-GGUF Bonsai-4B-gguf SD-1.5 --scenarios all`

now sends only the embed scenarios only to nomic-embed-text, only the textgen
scenarios only to bonsai-4b, and only the image generations to only SD-1.5.
Incompatible scenarios (eg. embed->SD, image->textgen) will be rejected

* remove unnecessary warmup runs

* remove format from image gen benchmarks

If response capture is turned on, the format is pinned to base64 so that it
is easily extracted from the log. If response capture is not enabled, the
format doesn't matter.

* warmup runs are not useful for image generation

pin them to 0 in the scenario parser in case someone tries it anyway

* removed unused `scenario_requires_capability()`